### ISSUE TITLE
Capable to disperse master nodes?

### ISSUE THREAD

**Issue by liuzhen** [ucloud/redis-cluster-operator#17]
Hi, for redis-cluster, master nodes have to be dispersed enough that there is not single machine where half master nodes are deployed (required by fail-over master election).

Do we have this built it?

**Comment by polefishu** [comment]
@liuzhen In V0.2.0，Each master and its slaves are managed by a separate statefulset. Each statefulset uses PodAntiAffinity to ensure that the master and slaves are dispersed on different nodes. At the same time, when the operator selects the master in each statefulset, it preferentially select the pod with different k8s nodes as master.
