### ISSUE TITLE
go mod download error with goland 1.13

### ISSUE THREAD

**Issue by thesunnysky** [ucloud/redis-cluster-operator#20]
go mod download with master branch error: 

go: github.com/appscode/go@v0.0.0-20191006073906-e3d193d493fc requires
        github.com/flosch/pongo2@v0.0.0-20181225140029-79872a7b2769 requires
        github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1

go: go version go1.13.1 linux/amd64

**Comment by polefishu** [comment]
fixed on branch v0.2.0, have try.

**Comment by thesunnysky** [comment]
there are also some else problems:
go: github.com/appscode/osm@v0.12.0 requires
	gomodules.xyz/stow@v0.2.0 requires
	github.com/Azure/go-autorest/autorest@v0.7.0 requires
	github.com/Azure/go-autorest/tracing@v0.4.0 requires
	contrib.go.opencensus.io/exporter/ocagent@v0.4.6 requires
	github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: reading https://goproxy.io/github.com/census-instrumentation/opencensus-proto/@v/v0.1.0-0.20181214143942-ba49f56771b8.mod: 404 Not Found

you may delete the local cache of go mod and then have try

**Comment by polefishu** [comment]
Did you customize the GOPROXY env?
You can try `docker build -t redis-cluster-operator:v0.2.0 -f Dockerfile .`
```
$ git clone git@github.com:ucloud/redis-cluster-operator.git
$ cd redis-cluster-operator
$ git checkout v0.2.0
$ git pull origin v0.2.0
$ docker build -t redis-cluster-operator:v0.2.0 -f Dockerfile .
```
