### ISSUE TITLE
Infinite error requeue in V0.2.0 during scale down.

### ISSUE THREAD

**Issue by ev-hines** [ucloud/redis-cluster-operator#21]
Version 0.2.0 should be able to handle scale down as per the commit history. When scaling down, an infinite requeue loop occurs with the cluster in an inconsistent state. 

The IP address of the pod isn't static. I am working on setting up an environment to turn on debug logging as I believe the error is related to the Admin.getInfos() function but I am unable to see any debug output other than the logs below.

It seems that the deleted master is still in the cluster node list but failing which is taking down the whole cluster. When this occurs, the scale down code is never reached as the error is caught and requeued earlier in the controller.

To reproduce:
Deploy the operator
Deploy the example at 4 nodes
Update the deployment to 3 nodes
Redeploy

Logs:

CheckRedisNodeNum: redis pods are not all ready

followed by an infinite loop of the following
` 
>>> Sending CLUSTER MEET messages to join the cluster
node xx.xx.x.x:6379 attached properly
wait for cluster join: Cluster view is inconsistent
...
>>> Sending CLUSTER MEET messages to join the cluster
node xy.xx.x.x:6379 attached properly
wait for cluster join: Cluster view is inconsistent
...
>>> Sending CLUSTER MEET messages to join the cluster
node zx.xx.x.x:6379 attached properly
wait for cluster join: Cluster view is inconsistent
`

**Comment by polefishu** [comment]
What's your operator image version? 
replace your image version with uhub.service.ucloud.cn/operator/redis-cluster-operator:v0.2.0

**Comment by ev-hines** [comment]
That was the problem. It seems the v0.2.0 branch still points its image to the master. Now I can't seem to get the cluster to fail. Well done!
