### ISSUE TITLE
Image versions should be fixed in manifest files

### ISSUE THREAD

**Issue by zedtux** [ucloud/redis-cluster-operator#28]
I'm deploying the version v0.2.0 from the `v0.2.0` tag which has the image `latest` tag for [the clustered](https://github.com/ucloud/redis-cluster-operator/blob/master/deploy/cluster/operator.yaml#L19) and the [namespaced](https://github.com/ucloud/redis-cluster-operator/blob/master/deploy/namespace/operator.yaml#L19) manifests which doesn't look right to me.

The `master` branch should use the `latest` docker image tag, no problem, but the releases should have a fixed docker image tag.

## Update

I found [this issue](https://github.com/ucloud/redis-cluster-operator/issues/21#issuecomment-568954049) where @polefishu suggest using the `v0.2.0` tag of the docker image, which seems to confirm the content of this issue.

**Comment by zedtux** [comment]
It would also be great to have a publicly accessible Docker registry where we can see the available tags.

**Comment by polefishu** [comment]
@zedtux Thanks, I have pushed the image to[ docker hub](https://hub.docker.com/repository/docker/fishu/redis-cluster-operator).
