### ISSUE TITLE
How to connect to Redis Pods during development?

### ISSUE THREAD

**Issue by theSupermacy** [ucloud/redis-cluster-operator#33]
I am trying to debug this package using 
`operator-sdk up local`
 and I am not able to connect to the Redis pods during development.

I think the main reason would be running the operator locally and the pod is inside the kubernetes cluster. 

It is working fine while running the operator inside the docker in the kubernetes cluster as a deployment. It would be tiring and long job to deploy every time in the cluster you make changes in the operator while debugging thus increasing the development time. 

How to connect to redis pod while doing development with just their IP ?

**Comment by polefishu** [comment]
Try using a tunnel to connect the network between the local and the cluster, or just use route.

**Comment by theSupermacy** [comment]
Route as in ? Can you be more declarative here ?
How do you connect two network using tunnel ?
What are you guys using for local Development?

**Comment by foxyriver** [comment]
config cluster-announce-ip as nodeIp:nodePort may resolve it. but how to edit DistributedRedisCluster CRD file to make different pod has different cluster-announce-ip configuration
