### ISSUE TITLE
Redundant Headless service 

### ISSUE THREAD

**Issue by theSupermacy** [ucloud/redis-cluster-operator#34]
These package creates **n headless service(equal to stateful set)**. What is the use of that Headless service as the pods are being accessed without the headless service using their IP?

**Comment by polefishu** [comment]
Kubernetes pods are volatile, they can be deleted and recreated, and pods IP will change when pod be recreated, and also, the IP will be recycled and redistributed to other pods. For this reason, some users want to access every redis node by domain name, so we create headless service for all statefulset.

**Comment by theSupermacy** [comment]
If you want to access every node with the service then the number of headless service should be equal to the number of the Pod. Actually redis client will try to connect with the redis Ip so there would be no use for the headless service again and also communication between redis node requires inter pod communication so service is not involved here.
