### ISSUE TITLE
Backup failed when master is down while doing backup

### ISSUE THREAD

**Issue by gaopenghigh** [ucloud/redis-cluster-operator#39]
If a backup job is running, and master died, backup will failed.
Logs show that redis client can not connect to master IP.

**Comment by polefishu** [comment]
When master died, the backup job still use died master IP, backup will always fail,the status of the backup is always running, When there is already a running backup, the next backup will never be executed.

Added ActiveDeadlineSeconds to backup job, once a Job reaches activeDeadlineSeconds, backup failed, then you can start next backup.

TODO: Automatically query the master node when do backup.
