### ISSUE TITLE
redis cluster is down after node recover from NotReady

### ISSUE THREAD

**Issue by xweijian** [ucloud/redis-cluster-operator#40]
deploy a redis cluster with 3 master and 3 slave
I kill one node's kubelet,then wait pods on this node turn to Terminating.
start kubelet,pod of statefulset reschedule and running state.
but nodes.conf have 8 nodes.all is master.

**Comment by polefishu** [comment]
Now only the redis cluster that use persistent storage can recover after accidental deletion, Are you using persistent storage?

**Comment by excieve** [comment]
@polefishu Is support for recovery from sudden k8s node termination without persistence enabled planned?

I'd expect that as long as Redis pods of a shard are on the different k8s nodes, if a single node is terminated at a time the StatefulSet should just auto-recover and cluster heal itself through replication. But it seems that something breaks and the cluster resource is stuck in the `Scaling` state. Is there a fundamental issue in this scenario that can't be done without persistence?
