### ISSUE TITLE
The rename of the config comand creates issue with the redis-py-cluster

### ISSUE THREAD

**Issue by usernkey** [ucloud/redis-cluster-operator#43]
rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, password='XXXXX')

Because the config command has been renamed the connection fails.

rediscluster.exceptions.RedisClusterException: ERROR sending 'config get cluster-require-full-coverage' command to redis server: {'host': '10.249.9.38', 'port': 6379, 'name': '10.249.9.38:6379', 'server_type': 'slave'}

As a workaround, you have to set skip_full_coverage_check=True. 

This might work on software built in the house but other software might not expose this configuration to the user.

rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=True, password='XXXXX')

**Comment by bsergean** [comment]
hey @usernkey fyi here's another redis python module which you might find useful.

https://github.com/machinezone/rcc/

It uses the INFO command to know if the remote machine is running in cluster mode, so it is not prone to this error. It is also asyncio based, so it's probably very different from redis-cluster module (and not as proven / solid likely, although it works for us).
