### ISSUE TITLE
The update of the operator get stuck

### ISSUE THREAD

**Issue by usernkey** [ucloud/redis-cluster-operator#45]
<img width="1504" alt="Screenshot 2020-05-14 at 15 25 03" src="https://user-images.githubusercontent.com/12896983/82072097-5bc51880-96d7-11ea-82b1-0b2e689eadaa.png">
                                                                           
When I try to change the version of the docker image the recycling of the pods get stuck because of some lock file.

{"level":"info","ts":1589462653.6875901,"logger":"cmd","msg":"Go Version: go1.13.3"}                                                                                         ││ {"level":"info","ts":1589462653.6877007,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}                                                                                      │
│ {"level":"info","ts":1589462653.6877236,"logger":"cmd","msg":"Version of operator-sdk: v0.13.0"}                                                                             ││ {"level":"info","ts":1589462653.6877367,"logger":"cmd","msg":"Version of operator: v0.2.0-34-dirty+7494848"}                                                                 │
│ {"level":"info","ts":1589462653.77739,"logger":"leader","msg":"Trying to become the leader."}                                                                                ││ {"level":"info","ts":1589462654.48222,"logger":"leader","msg":"Found existing lock","LockOwner":"redis-cluster-operator-56f8d58767-rn8nd"}                                   │
│ {"level":"info","ts":1589462654.4928203,"logger":"leader","msg":"Not the leader. Waiting."}

**Comment by usernkey** [comment]
Workaround is kill manualy the old pod so lock get released and new pod start. You might need to try few times. :)

**Comment by polefishu** [comment]
During the lifecycle of an operator it’s possible that there may be more than 1 instance running at any given time e.g when rolling out an upgrade for the operator. 
Click for more [details](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#leader-election)
