### ISSUE TITLE
Openshift : /bin/sh: can't create /etc/redis_password: Permission denied

### ISSUE THREAD

**Issue by hufon** [ucloud/redis-cluster-operator#47]
Since this commit  https://github.com/ucloud/redis-cluster-operator/commit/92111c759e5fd3b5895c7622c2accf22e32522f7

We couldn't deploy redis operator on openshift.
/etc is readonly on openshift, and we don't use REDIS_PASSWORD.

**Comment by hufon** [comment]
Maye be adding a password != nil when adding the poststart hook

**Comment by hufon** [comment]
/etc/redis_password should be moved in a ephemeral volume.

**Comment by bsergean** [comment]
Hey @hufon I'd like to try this operator but we use OpenShift 3.11. Which version of OpenShift are you guys using ?

**Comment by hufon** [comment]
We use okd/openshift 3.11

**Comment by bsergean** [comment]
Thanks, it's good for us as we are using the same version, and I thought that this operator wasn't supported.

**Comment by bsergean** [comment]
@hufon are you currently using the password protection and are blocked because of this, or is 'everything broken', even in password-less mode after 92111c7 ?

**Comment by bsergean** [comment]
I have setup minishift locally and I am also running into this problem. oc get events show

**Could /tmp/ be used instead of /etc for temp files ?**

```
NAME                                       READY   STATUS              RESTARTS   AGE
drc-example-distributedrediscluster-1-0    0/1     PostStartHookError: command '/bin/sh -c echo ${REDIS_PASSWORD} > /etc/redis_password' exited with 1: /bin/sh: can't create /etc/redis_password: Permission denied
                                           0       6h8m
drc-example-distributedrediscluster-0-0    0/1     PostStartHookError: command '/bin/sh -c echo ${REDIS_PASSWORD} > /etc/redis_password' exited with 1: /bin/sh: can't create /etc/redis_password: Permission denied
                                           0       6h8m
drc-example-distributedrediscluster-2-0    0/1     PostStartHookError: command '/bin/sh -c echo ${REDIS_PASSWORD} > /etc/redis_password' exited with 1: /bin/sh: can't create /etc/redis_password: Permission denied
                                           0       6h8m
^C%                                                                                                       
```

**Comment by bsergean** [comment]
Or maybe /var, or /data (alongside /data/nodes.conf) ?

**Comment by bsergean** [comment]
I've forked the repo, used /data instead of /etc, rebuilt the operator and pushed it to our own internal docker registry and that works.

https://github.com/bsergean/redis-cluster-operator/commit/dd55c2c513d7708b986791f4d9eb182fa341666b

Putting the password in /data isn't the right solution, but that's a workaround for now if anyone needs one.
