### ISSUE TITLE
Redis Connectivity 

### ISSUE THREAD

**Issue by pashafirdous** [ucloud/redis-cluster-operator#59]
Hi,
Could you provide me any documentatin to understand the operator or can we have a section for redis connectivity in the readme?

we are looking for some assistance to know the operator details to use it in our production.
regards,

**Comment by polefishu** [comment]
Why not! I will provide a Chinese document first.

**Comment by polefishu** [comment]
> Why not! I will provide a Chinese document first.

https://github.com/ucloud/redis-cluster-operator/pull/65
