### ISSUE TITLE
Provide user guide about local build

### ISSUE THREAD

**Issue by simonhou** [ucloud/redis-cluster-operator#62]
Hi, I'd like to add some customized features. Could you please provide a user guide?

**Comment by simonhou** [comment]
@polefishu Can you help it?

**Comment by polefishu** [comment]
> @polefishu Can you help it?

To compile the binary locally, execute the command in the project path:

`make build-go`

To build images, execute the command in the project path:

`make build-image`

You can find more details in the Makefile.

**Comment by simonhou** [comment]
Thanks, it works fine.
