### ISSUE TITLE
Helm installation guide

### ISSUE THREAD

**Issue by kyue1005** [ucloud/redis-cluster-operator#63]
Is it possible to provide a guide on installation using helm? 
etc. the helm repo URL

**Comment by kyue1005** [comment]
It would be great to host the chart repo in GitHub, then user able to use helm command to pull the chart

https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kd

**Comment by polefishu** [comment]
> It would be great to host the chart repo in GitHub, then user able to use helm command to pull the chart
> 
> https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kd

That' s a great idea.
