### ISSUE TITLE
make build-image fail

### ISSUE THREAD

**Issue by mathslimin** [ucloud/redis-cluster-operator#68]
```
make build-image
```
docker build --build-arg VERSION=v0.2.3-26 --build-arg GIT_SHA=a01fa97 -t /redis-cluster-operator:v0.2.3-26 .
invalid argument "/redis-cluster-operator:v0.2.3-26" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [build-image] Error 125

**Comment by polefishu** [comment]
You need to set the `DOCKER_REGISTRY` variable:
```
DOCKER_REGISTRY=<your registry> make build-image
```
