### ISSUE TITLE
PostStartHookError

### ISSUE THREAD

**Issue by shixinghong** [ucloud/redis-cluster-operator#76]
I want to use the definition password  , then I have changed the "custom-password.yaml" ,Change the `password: MWYyZDFlMmU2N2Rm` to `password: MTIzNDU2Cg==`  
`kubeclt apply -f custom-password.yaml ` ,There's an error "PostStartHookError: command '/bin/sh -c echo ${REDIS_PASSWORD} > /data/redis_password' exited with 126:    0 " 
` kubectl logs -f  drc-redis-cluster-0-0 `   ,like this 
`*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 4
>>> 'requirepass '123456'
Unbalanced quotes in configuration line
`

**Comment by xmanta** [comment]
you can stringData

**Comment by xmanta** [comment]
> I want to use the definition password , then I have changed the "custom-password.yaml" ,Change the `password: MWYyZDFlMmU2N2Rm` to `password: MTIzNDU2Cg==`
> `kubeclt apply -f custom-password.yaml ` ,There's an error "PostStartHookError: command '/bin/sh -c echo ${REDIS_PASSWORD} > /data/redis_password' exited with 126: 0 "
> `kubectl logs -f drc-redis-cluster-0-0` ,like this
> `*** FATAL CONFIG FILE ERROR ***
> Reading the configuration file, at line 4
> 
> > > > 'requirepass '123456'
> > > > Unbalanced quotes in configuration line
> > > > `

you can use stringData

**Comment by shixinghong** [comment]
I have solved it，thx !
